### ISSUE TITLE
Is it ideal to put all of the frontend under resources?

### ISSUE THREAD

**Issue by qiuwei** [spring-guides/tut-react-and-spring-data-rest#10]
I followed your approach to build an application with slightly larger frontend.
Then there is a huge amount of files under node_modules which causes my IDE hang during compiling.

I think it might be a good idea just to put the built/bundle.js under resources, and keep other stuff in the src code directory.

**Comment by gregturn** [comment]
The files will be in your IDE either way. What difference does it make in that regard? Did you move them to src and see a speed up?

**Comment by qiuwei** [comment]
They won't get copied to target.

Yes, I moved them to src, make webpack generate the bundle.js in resources.

In the ide, I then explicitly exclude those node_modules directory.

It's much faster:)

**Comment by abhiesa-tolexo** [comment]
+1
@qiuwei Could you please let me know, how did you achieve this ?

**Comment by qiuwei** [comment]
@abhiesa-tolexo ,

I create a directory under src, move front-end related code there, then change the output in `webpack.config.js` to `../resource/static/build/bunlde.js`

I also exclude `node_modules` directory in my IDE explictly.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-guides/tut-react-and-spring-data-rest/commit/10b5db5d70bb6bd3a80cf5001b1c5b17f670bd43
