### ISSUE TITLE
Parts 3, 4, 5 not linked

### ISSUE THREAD

**Issue by jugutier** [spring-guides/tut-react-and-spring-data-rest#103]
When accessing the website, only part 2 and 3 are visible. Looks like some links got broke with the last update.

**Comment by MaggiWuerze** [comment]
would be really glad if this could be fixed, makes this otherwise great tutorial basically unreadable.
I also noticed that some links in the first two parts are broken as well

**Comment by mrsarm** [comment]
This is related with this error for sure: #105

**Comment by MiloBem** [comment]
fixed by #107

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-guides/tut-react-and-spring-data-rest/commit/d957d773219f0809588031b64d4ce96c3e356bff.
