### ISSUE TITLE
bundle.js is not loaded, error 302

### ISSUE THREAD

**Issue by IngilevichV** [spring-guides/tut-react-and-spring-data-rest#104]
In my login.html page I have specifed the div with id "react":

` <div id="react"/>`

The file bundle.js is generated correctly, but when the page login.html loads, it cannot load the script bundle.js, and I always get the error 302.

**Comment by Carpathea** [comment]
I get a 404 on the bundle.js

**Comment by gregturn** [comment]
Simply put, anything found in `src/main/resources/static` gets copied into `target/classes/static`, from where it will be served up by Spring Boot.

For this tutorial, I have webpack building `src/main/resources/static/built/bundle.js` (that let's me flag `built` as a folder for git to ignore). To load it, I have to do this:

```html
<script src="built/bundle.js"></script>
```

You need to run `./mvnw package` and verify the path to your `bundle.js` in the `target` folder. Without more details about your setup, not sure I can help you.

**Comment by gregturn** [comment]
Feel free to reopen if this issue continues to plague you.
