### ISSUE TITLE
Can not load employees using new loadFromServer method

### ISSUE THREAD

**Issue by tur-ing** [spring-guides/tut-react-and-spring-data-rest#11]
In the past (basic) tutorial everything worked fine. Now I have some trouble loading employees using the loadFromServer method.

- I do not receive the employees to display them in the table.

![bildschirmfoto 2016-02-14 um 15 29 18](https://cloud.githubusercontent.com/assets/15199933/13034218/f3e60cac-d32f-11e5-8b25-f4a6eb50d42a.png)

**Line 279** is the `var inputs` part of UpdateDialog

       render() {
		var inputs = this.props.attributes.map(attribute =>
				<p key={this.props.farmer.entity[attribute]}>
					<input type="text" placeholder={attribute}
						   defaultValue={this.props.farmer.entity[attribute]}
						   ref={attribute} className="field" />
				</p>
	);

Accessing /api returns

![bildschirmfoto 2016-02-14 um 15 32 42](https://cloud.githubusercontent.com/assets/15199933/13034230/3a303930-d330-11e5-89d4-0f97152e6b52.png)

What might be the problem here?

**Comment by gregturn** [comment]
What is "props.farmer"?  Are you adapting the tutorial to a problem of yours? What changes have you made to do so.

**Comment by tur-ing** [comment]
Yes, I adapted "employee" to "farmer" - but that's it. I have setup two different REST Services but none of them work with the loadFromServer method. I will provide you the full source code in a repo - that makes it more concrete.

**Comment by tur-ing** [comment]
Please tell me if you need more information

**Comment by tur-ing** [comment]
OK, I removed the whole "Update" functionality - the modal and the methods. Now I can see the table entries again. It seems to be an issue with part on Line 279 I posted before.

**Comment by gregturn** [comment]
You've made so many changes it might be difficult to eyeball through a few bits. You may want to start sprinkling in some console.log statements, especially where things are breaking.

**Comment by gregturn** [comment]
It's complaining that "map" is being run against an undefined which hints that this.props.attributes isn't defined. Check if the render() call that creates` <UpdateDialog>` is passing in something to that particular property correctly. `console.log(this.props.attributes)` right inside `render()` might be handy to verify the right data is getting passed into that component.

**Comment by tur-ing** [comment]
OK, I am going to find out why the `this.props.attributes` is not set correctly. I am closing this issue for now because it's a bit off-topic compared to the actual tutorial.
Thank you Greg!
