### ISSUE TITLE
webpack issues, blank view

### ISSUE THREAD

**Issue by AustinSong** [spring-guides/tut-react-and-spring-data-rest#12]
Hello!
I have some issues with running the first part of the tutorial.  When I run it, the view is blank.  I checked the web inspector and it tells me it is unable to load the bundle.js resource.  I think it might have something to do with the webpack. 

Maybe it has something to do with my IDE module settings?

Here is my pom.xml

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.github.AustinSong</groupId>
	<artifactId>BookExchange</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>BookExchange</name>
	<description>web app for exchange of text books</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.3.2.RELEASE</version>
		<relativePath/> 
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-thymeleaf</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-rest</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.16.4</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>

			<plugin>
				<groupId>com.github.eirslett</groupId>
				<artifactId>frontend-maven-plugin</artifactId>
				<version>0.0.24</version>
				<configuration>
					<workingDirectory>src/main/resources/static</workingDirectory>
				</configuration>
				<executions>
					<execution>
						<id>install node and npm</id>
						<goals>
							<goal>install-node-and-npm</goal>
						</goals>
						<configuration>
							<nodeVersion>v0.10.33</nodeVersion>
							<npmVersion>1.3.8</npmVersion>
						</configuration>
					</execution>
					<execution>
						<id>npm install</id>
						<goals>
							<goal>npm</goal>
						</goals>
						<configuration>
							<arguments>install</arguments>
						</configuration>
					</execution>
					<execution>
						<id>webpack build</id>
						<goals>
							<goal>webpack</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

</project>`

There's the error with web pack that I receive in the IDE.  I'm using STS btw

<img width="1552" alt="screen shot 2016-02-18 at 4 27 00 pm" src="https://cloud.githubusercontent.com/assets/7930314/13162909/739792e2-d65d-11e5-8277-e08875e61eec.png">

**Comment by gregturn** [comment]
In your screenshot, I see neither a package.json file nor a webpack.config.js file (as you can see [here](https://github.com/spring-guides/tut-react-and-spring-data-rest/tree/master/basic/src/main/resources/static)). 

package.json is required to know what modules to load (including webpack). The webpack.config.js is needed to tell webpack how to build and assemble bunde.js.

**Comment by AustinSong** [comment]
Thanks for the quick advice.  
I've since added all of the files within the static folder on the github page.

My errors have disappeared after adding <pluginManagement> tags to my pom file.  

I copied the contents from the github repository and put them into my project.
I'm still receiving a Not found resource.  Here are the screenshots of the updated project view and error message

<img width="1552" alt="screen shot 2016-02-18 at 6 31 11 pm" src="https://cloud.githubusercontent.com/assets/7930314/13164977/fe021474-d66d-11e5-806c-2aee314d3847.png">
<img width="1240" alt="screen shot 2016-02-18 at 6 31 34 pm" src="https://cloud.githubusercontent.com/assets/7930314/13164979/fe1c9c2c-d66d-11e5-8b6e-1d893a5028e0.png">

**Comment by AustinSong** [comment]
So I've managed to create the build.   I've got a new error when loading.  
Here is a screen.

<img width="1237" alt="screen shot 2016-02-18 at 10 11 31 pm" src="https://cloud.githubusercontent.com/assets/7930314/13167930/bab88d5a-d68c-11e5-9cd4-a151750d001f.png">

**Comment by AustinSong** [comment]
I was able to get the table to show up now.  I realized that the class being extended in app.js was React.component rather than React.Component.

I also had execute webpack on the static folder via the terminal to update the app.js. 

Is there a better way for the project to update the js files from the static folder other than having to do webpack when I need to update?

**Comment by gregturn** [comment]
Here is webpack's command to remain in watch mode, where it recompiles and hot-reloads as you make edits => https://github.com/spring-guides/tut-react-and-spring-data-rest/blob/master/basic/src/main/resources/static/package.json#L30

I have it wrapped as an npm task, so I don't have to remember the whole command.

It's important to understand that Spring Boot's DevTools LiveReload feature doesn't monitor resource updates to refresh the app context, so you'll probably have to refresh the browser.

**Comment by gregturn** [comment]
Seeing you having resolved this issue, can we close it?

**Comment by AustinSong** [comment]
Yes thank you so much.
