### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by abhiesa-tolexo** [spring-guides/tut-react-and-spring-data-rest#14]
1)  Could you please include test cases, definitely i can create a pull request, still before doing so, need suggestions.

2) Tutorial is a JS rich in nature, and JS test cases (Mocha/Chai/Sinon/Karma) integration is a welcome, with devtools, reloading generated js, as we develop.

Yes, i am aware, this too much too ask, still just a humble request.
I am pretty shy with anything with word JS in it, so would not be much use on above request stack. :crying_cat_face:

**Comment by gregturn** [comment]
I would like to eventually build up some unit testing, but it's pretty low on my priority. Sorry!

**Comment by gregturn** [comment]
I personally don't have the bandwidth to pursue this. If you wish to write test cases, whether it's JS or Java, I would welcome it.
