### ISSUE TITLE
Enable CORS at AbstractWebSocketMessageBrokerConfigurer

### ISSUE THREAD

**Issue by tur-ing** [spring-guides/tut-react-and-spring-data-rest#16]
I want to access the WebSocket from another host. I tried to set the `.setAllowedOrigins("*")` to enable CORS like this, which does not work:
```

@Component
@EnableWebSocketMessageBroker
public class WebSocketConfiguration extends AbstractWebSocketMessageBrokerConfigurer {

	public static final String MESSAGE_PREFIX = "/topic";

	@Override
	public void registerStompEndpoints(StompEndpointRegistry registry) {
		registry.addEndpoint("/payroll").setAllowedOrigins("*").withSockJS();
	}

	@Override
	public void configureMessageBroker(MessageBrokerRegistry registry) {
		registry.enableSimpleBroker(MESSAGE_PREFIX);
		registry.setApplicationDestinationPrefixes("/app");
	}
	
}
```

**Comment by tur-ing** [comment]
OK, seems that this is not related to a CORS problem - it is more an authorization problem! The host is protected by Spring Security, so the socket listener can not access it (401 error).

Acutually, I would like to go through **Zuul**. Everything is working fine there now. But Zuul does not seem to have WebSocket proxy abilities.

**Comment by gregturn** [comment]
That may a bit out of scope for what we want to cover in this tutorial.

Have you looked at https://spring.io/guides/tutorials/spring-security-and-angular-js/? I realize it's Angular and you are using React, but they cover a lot of stuff you are alluding to such as Spring Security, Zuul, and OAuth2. You might want to skim over it, and see if it addresses the issues you interested in tackling.

**Comment by tur-ing** [comment]
OK. @gregturn if you need ideas for a new tutorial, I have a lot of them ;-)

**Comment by gregturn** [comment]
My desire for new tutorials is hedged by my ability to maintain them. ;)
