### ISSUE TITLE
Enable some navigation in React.js

### ISSUE THREAD

**Issue by tur-ing** [spring-guides/tut-react-and-spring-data-rest#17]
How does implementing a navigation work in React.js in context to this tutorial? It seems that there is some kind of routing at the end of the URL (`http://localhost:8080/login`) which could be used to load the appropriate components.

I have no idea :) and appreciate any support to understand how a navigation could work.

For example: two different tables loading data from two different endpoints

**Comment by gregturn** [comment]
For the record, this app doesn't really do routing. It's essentially a SPA (Single Page App). There is a form login, but that is provided by Spring Security.

For an app that needs routing, you may wish to investigate the React community and look at routing options (like https://github.com/reactjs/react-router for example).
