### ISSUE TITLE
Problem with client.js (/api/uriTemplateInterceptor")

### ISSUE THREAD

**Issue by mkiuser** [spring-guides/tut-react-and-spring-data-rest#18]
Hi,

i'm having a problem with the client.js. Maven gives following Info

[INFO] ERROR in ./client.js
[INFO] Module not found: Error: Cannot resolve 'file' or 'directory' ./api/uriTemplateInterceptor in /src/main/resources/static
[INFO]  @ ./client.js 9:29-68
[INFO] 
[INFO] ERROR in ./client.js
[INFO] Module not found: Error: Cannot resolve 'file' or 'directory' ./api/uriListConverter in /src/main/resources/static
[INFO]  @ ./client.js 15:35-68

and in Chrome browser the Console says:
Cannot find module "./api/uriTemplateInterceptor"

Do you know how i can fix that?

Best Greetings!

**Comment by gregturn** [comment]
Which section of the tutorial are you hitting this problem?

**Comment by mkiuser** [comment]
Uff, Sorry i didn't check out the static/api/ folder my bad!

**Comment by elibeta22** [comment]
what do you mean you didnt check out static/api/folder?

**Comment by EricTheRed-VT** [comment]
Is there a fix for this? I can't find any api folder in my project or here on github.

**Comment by gregturn** [comment]
Since the original op closed the issue I figured there was nothing to solve. 

The tutorial uses webpack to compile all the JavaScript into a bundle. Please describe the steps you go through to produce this error in a new ticket.

**Comment by MartinHein** [comment]
@gregturn I had the same problem. I took these files from your repository to solve it:

![image](https://user-images.githubusercontent.com/4800631/37518003-b290b3ba-2913-11e8-81ec-9f47679e134e.png)

In these tutorial (https://spring.io/guides/tutorials/react-and-spring-data-rest/) nobody shows these files. They are generated automatically?

**Comment by gregturn** [comment]
There are links to both `webpack.config.js` and `client.js` so you can read that stuff quite easily. But this is really plumbing code and in my opinion would slow things down. I tried to make it clear this tutorial doesn't focus on webpack and other things, but instead about doing hypermedia.

The focus of the tutorial is meant to be React components you build that are capable of navigating HAL hypermedia, with the assumption being you can check out ALL the code to look at the guts of it if you wanted.

**Comment by leoncordell** [comment]
> 
> 
> There are links to both `webpack.config.js` and `client.js` so you can read that stuff quite easily. But this is really plumbing code and in my opinion would slow things down. I tried to make it clear this tutorial doesn't focus on webpack and other things, but instead about doing hypermedia.
> 
> The focus of the tutorial is meant to be React components you build that are capable of navigating greg ,  I like the article  but I spent  hours wasted  simply  because  you dont mention these two  files. One sentence  would  have  saved the time. Everything  else  worked.

**Comment by leoncordell** [comment]
I liked the  article, but should  have mentioned the  essential  files .Would  have  saved me  a few  hours.
