### ISSUE TITLE
Cannot find module 'crypto-browserify'

### ISSUE THREAD

**Issue by baconbyte** [spring-guides/tut-react-and-spring-data-rest#19]
I'm getting the below error when trying to run the latest verison of the basic project, any ideas on what's causing it. I tried updating the the frontend-maven-pligin to 0.0.28 but I still get the same error.

./mvnw spring-boot:run
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building React.js and Spring Data REST - Basic 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> spring-boot-maven-plugin:1.3.3.RELEASE:run (default-cli) > test-compile @ react-and-spring-data-rest-basic >>>
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.24:install-node-and-npm (install node and npm) @ react-and-spring-data-rest-basic ---
[INFO] Node v0.10.33 is already installed.
[INFO] Found NPM version 1.3.8
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.24:npm (npm install) @ react-and-spring-data-rest-basic ---
[INFO] Running 'npm install --color=false' in /Users/davidbacon/Dev/workspaces/tut-react-and-spring-data-rest/basic/src/main/resources/static
[ERROR] npm WARN package.json spring-data-rest-and-reactjs@0.1.0 No README data
[ERROR] npm WARN unmet dependency /Users/davidbacon/Dev/workspaces/tut-react-and-spring-data-rest/basic/src/main/resources/static/node_modules/babel-core/node_modules/source-map-support requires source-map@'0.1.32' but will load
[ERROR] npm WARN unmet dependency undefined,
[ERROR] npm WARN unmet dependency which is version undefined
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.24:webpack (webpack build) @ react-and-spring-data-rest-basic ---
[INFO] Running 'webpack.js --no-color' in /Users/davidbacon/Dev/workspaces/tut-react-and-spring-data-rest/basic/src/main/resources/static
[ERROR] 
[ERROR] module.js:340
[ERROR]     throw err;
[ERROR]           ^
[ERROR] Error: Cannot find module 'crypto-browserify'
[ERROR]     at Function.Module._resolveFilename (module.js:338:15)
[ERROR]     at Function.require.resolve (module.js:384:19)
[ERROR]     at Object.<anonymous> (/Users/davidbacon/Dev/workspaces/tut-react-and-spring-data-rest/basic/src/main/resources/static/node_modules/webpack/node_modules/node-libs-browser/index.js:7:31)
[ERROR]     at Module._compile (module.js:456:26)
[ERROR]     at Object.Module._extensions..js (module.js:474:10)
[ERROR]     at Module.load (module.js:356:32)
[ERROR]     at Function.Module._load (module.js:312:12)
[ERROR]     at Module.require (module.js:364:17)
[ERROR]     at require (module.js:380:17)
[ERROR]     at Object.<anonymous> (/Users/davidbacon/Dev/workspaces/tut-react-and-spring-data-rest/basic/src/main/resources/static/node_modules/webpack/lib/node/NodeSourcePlugin.js:7:23)
[ERROR]     at Module._compile (module.js:456:26)
[ERROR]     at Object.Module._extensions..js (module.js:474:10)
[ERROR]     at Module.load (module.js:356:32)
[ERROR]     at Function.Module._load (module.js:312:12)
[ERROR]     at Module.require (module.js:364:17)
[ERROR]     at require (module.js:380:17)
[ERROR]     at OptionsApply.WebpackOptionsApply.process (/Users/davidbacon/Dev/workspaces/tut-react-and-spring-data-rest/basic/src/main/resources/static/node_modules/webpack/lib/WebpackOptionsApply.js:72:28)
[ERROR]     at webpack (/Users/davidbacon/Dev/workspaces/tut-react-and-spring-data-rest/basic/src/main/resources/static/node_modules/webpack/lib/webpack.js:22:48)
[ERROR]     at processOptions (/Users/davidbacon/Dev/workspaces/tut-react-and-spring-data-rest/basic/src/main/resources/static/node_modules/webpack/bin/webpack.js:152:17)
[ERROR]     at Object.<anonymous> (/Users/davidbacon/Dev/workspaces/tut-react-and-spring-data-rest/basic/src/main/resources/static/node_modules/webpack/bin/webpack.js:192:1)
[ERROR]     at Module._compile (module.js:456:26)
[ERROR]     at Object.Module._extensions..js (module.js:474:10)
[ERROR]     at Module.load (module.js:356:32)
[ERROR]     at Function.Module._load (module.js:312:12)
[ERROR]     at Function.Module.runMain (module.js:497:10)
[ERROR]     at startup (node.js:119:16)
[ERROR]     at node.js:906:3
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.720 s
[INFO] Finished at: 2016-03-13T20:59:23+00:00
[INFO] Final Memory: 16M/368M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.24:webpack (webpack build) on project react-and-spring-data-rest-basic: Failed to run task: 'webpack.js --no-color' failed. (error code 8) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by gregturn** [comment]
I just cloned and ran the tutorial's basic section, and it worked fine. I've seen npm get fickled and fail a download, so my suggestion is to try again.

```
$ git clone git@github.com:spring-guides/tut-react-and-spring-data-rest.git
Cloning into 'tut-react-and-spring-data-rest'...
remote: Counting objects: 927, done.
remote: Total 927 (delta 0), reused 0 (delta 0), pack-reused 927
Receiving objects: 100% (927/927), 1.61 MiB | 1.68 MiB/s, done.
Resolving deltas: 100% (513/513), done.
Checking connectivity... done.
$ cd tut-react-and-spring-data-rest/
$ cd basic
$ ./mvnw spring-boot:run
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building React.js and Spring Data REST - Basic 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> spring-boot-maven-plugin:1.3.3.RELEASE:run (default-cli) > test-compile @ react-and-spring-data-rest-basic >>>
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.24:install-node-and-npm (install node and npm) @ react-and-spring-data-rest-basic ---
[INFO] Installing node version v0.10.33
[INFO] Creating temporary directory /private/tmp/tut-react-and-spring-data-rest/basic/node_tmp
[INFO] Downloading Node.js from http://nodejs.org/dist/v0.10.33/node-v0.10.33-darwin-x64.tar.gz to /private/tmp/tut-react-and-spring-data-rest/basic/node_tmp/node.tar.gz
[INFO] No proxy was configured, downloading directly
[INFO] Extracting Node.js files in node_tmp
[INFO] Unpacking /private/tmp/tut-react-and-spring-data-rest/basic/node_tmp/node.tar.gz into /private/tmp/tut-react-and-spring-data-rest/basic/node_tmp
[INFO] Moving node binary to /private/tmp/tut-react-and-spring-data-rest/basic/node/node
[INFO] Deleting temporary directory /private/tmp/tut-react-and-spring-data-rest/basic/node_tmp
[INFO] Installed node locally.
[INFO] Installing npm version 1.3.8
[INFO] Downloading NPM from http://registry.npmjs.org/npm/-/npm-1.3.8.tgz to /private/tmp/tut-react-and-spring-data-rest/basic/npm.tar.gz
[INFO] No proxy was configured, downloading directly
[INFO] Extracting NPM files in node/
[INFO] Unpacking /private/tmp/tut-react-and-spring-data-rest/basic/npm.tar.gz into /private/tmp/tut-react-and-spring-data-rest/basic/node
[INFO] Installed NPM locally.
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.24:npm (npm install) @ react-and-spring-data-rest-basic ---
[INFO] Running 'npm install --color=false' in /private/tmp/tut-react-and-spring-data-rest/basic/src/main/resources/static
[ERROR] npm WARN package.json spring-data-rest-and-reactjs@0.1.0 No README data
[ERROR] npm http GET https://registry.npmjs.org/babel-loader
[ERROR] npm http GET https://registry.npmjs.org/react
...
...
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.24:webpack (webpack build) @ react-and-spring-data-rest-basic ---
[INFO] Running 'webpack.js --no-color' in /private/tmp/tut-react-and-spring-data-rest/basic/src/main/resources/static
[INFO] Hash: 64d532c18fb971535b64
[INFO] Version: webpack 1.12.14
[INFO] Time: 1653ms
[INFO]                 Asset    Size  Chunks             Chunk Names
[INFO]     ./built/bundle.js  783 kB       0  [emitted]  main
[INFO] ./built/bundle.js.map  937 kB       0  [emitted]  main
[INFO]     + 205 hidden modules
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ react-and-spring-data-rest-basic ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 5361 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ react-and-spring-data-rest-basic ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to /private/tmp/tut-react-and-spring-data-rest/basic/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ react-and-spring-data-rest-basic ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /private/tmp/tut-react-and-spring-data-rest/basic/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ react-and-spring-data-rest-basic ---
[INFO] No sources to compile
[INFO] 
[INFO] <<< spring-boot-maven-plugin:1.3.3.RELEASE:run (default-cli) < test-compile @ react-and-spring-data-rest-basic <<<
[INFO] 
[INFO] --- spring-boot-maven-plugin:1.3.3.RELEASE:run (default-cli) @ react-and-spring-data-rest-basic ---

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.3.3.RELEASE)

2016-03-14 10:10:14.709  INFO 34412 --- [           main] c.g.p.ReactAndSpringDataRestApplication  : Starting ReactAndSpringDataRestApplication on retina with PID 34412 (/private/tmp/tut-react-and-spring-data-rest/basic/target/classes started by gturnquist in /private/tmp/tut-react-and-spring-data-rest/basic)
...
...
2016-03-14 10:10:19.070  INFO 34412 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
2016-03-14 10:10:19.124  INFO 34412 --- [           main] c.g.p.ReactAndSpringDataRestApplication  : Started ReactAndSpringDataRestApplication in 4.708 seconds (JVM running for 25.494)
```
