### ISSUE TITLE
JSXTransformer error

### ISSUE THREAD

**Issue by stefanm7** [spring-guides/tut-react-and-spring-data-rest#2]
Just cloned the master, did `maven install` for basic-project and started it.
When accessing localhost:8080 a blank page is shown, with this errors showing up in the console:

`require.js:1952 GET http://localhost:8080/bower_components/react/JSXTransformer.js req.load @ require.js:1952context.load @ require.js:1679Module.load @ require.js:829Module.fetch @ require.js:819Module.check @ require.js:851Module.enable @ require.js:1177context.enable @ require.js:1550(anonymous function) @ require.js:1162(anonymous function) @ require.js:131each @ require.js:56Module.enable @ require.js:1114Module.init @ require.js:783(anonymous function) @ require.js:1453
require.js:165 Uncaught Error: Script error for "JSXTransformer/JSXTransformer"
http://requirejs.org/docs/errors.html#scripterror`

**Comment by gregturn** [comment]
What do you mean you did "maven install and started it"?

When I run maven install, I see this:

```
[INFO] Installing /private/tmp/tut-react-and-spring-data-rest/basic/target/react-and-spring-data-rest-basic-0.0.1-SNAPSHOT.jar to /Users/gturnquist/.m2/repository/com/greglturnquist/react-and-spring-data-rest-basic/0.0.1-SNAPSHOT/react-and-spring-data-rest-basic-0.0.1-SNAPSHOT.jar
[INFO] Installing /private/tmp/tut-react-and-spring-data-rest/basic/pom.xml to /Users/gturnquist/.m2/repository/com/greglturnquist/react-and-spring-data-rest-basic/0.0.1-SNAPSHOT/react-and-spring-data-rest-basic-0.0.1-SNAPSHOT.pom
```

This installs the built JAR into my local maven repo, but doesn't run anything. 

The recommendation from the tutorial is `./mvnw spring-boot:run`. When I do that, it runs fine for me.

**Comment by gregturn** [comment]
BTW, the master should show no more bower modules (npm instead) and no more require.js (webpack instead). Don't know how you got that if you just cloned the master since those changes were made almost two weeks ago.

**Comment by stefanm7** [comment]
> What do you mean you did "maven install and started it"?
I meant that i executed `maven install` and then started the application (did not mean that `maven install`started it).

Meanwhile i found the cause of this "error":
In the tutorial:
https://spring.io/blog/2015/09/01/react-js-and-spring-data-rest-part-1-basic-features
in "Step 0" there is a "grab code" - link to https://github.com/gregturn/react-and-spring-data-rest/tree/master/basic -> this repo has the error, and this was the one i cloned.
When experiencing the errors i searched for the project on github and came here (did not recognize that it is a different repo yesterday)

It would be good to change the link in the tutorial.
Thanks for your great tutorial and the quick answer.

**Comment by gregturn** [comment]
Okay, that is the blog article linking to the old code, not the tutorial itself. I will go back to the blog articles and put a header linking to the new tutorial at the top. Sound like a plan?
