### ISSUE TITLE
Port examples to Gradle/Groovy and update to Spring Boot 1.4.0.M2

### ISSUE THREAD

**Issue by MHarris021** [spring-guides/tut-react-and-spring-data-rest#22]
I would like to see these examples using Gradle and Groovy with an update for using New Features in Spring Boot 1.4.0.M2.  I've begun work here: https://github.com/DarcStarSolutions/webjars-webpack-with-gradle . My project needs to be renamed and there are some tweaks that need to be done because of the gradle plugin. As Gradle doesn't have a comparable plugin to Maven FrontEnd by default, I'm using the Gradle Node Plugin; it can be found here: https://github.com/srs/gradle-node-plugin . I'm happy to contribute/collaborate on this.

Currently, I have the basic and hypermedia projects working correctly.

**Comment by gregturn** [comment]
Your proposal looks very interesting. However, there are some things we have to go over before I can accept such a proposal.

1. You have to be willing to sign our CLA => https://support.springsource.com/spring_committer_signup
1. For this effort to turn into a pull request and be mergeable upstream, you need to start from a proper fork. You appear to have a completely new repo which will induce more work on my end than I'm willing to take on.
1. In general, we keep the guides on stable releases, except for special situations. Hence, I'm not willing to migrate to Spring Boot 1.4.0.M2 at this point in time. When 1.4 goes GA, we could revisit updates at that point in time.
1. Given the tutorial is focused on code, not build systems, I see it as no problem at all to introduce a gradle-based set of build scripts. I'm sure that would increase the interest of the tutorial without cluttering it up in any way.

If this sounds like an agreeable list, then we can move forward.

**Comment by MHarris021** [comment]
@gregturn 
Greg,

1. I am happy to sign the CLA, which project do I set it to? I didn't see a Spring-Guides Project category.
2. I can do a fork off the code and add in the gradle build, the only issue was I rewrote the source code as Groovy instead of Java. Easy enough to switch back. Or I could create Groovy versions of each project and have them co-exist, i.e basic and basic-groovy, etc... Your choice. 
3. I can wait until Spring Boot 1.4 goes GA, I wanted to test out the automatic @Autowired feature for single constructors. I can easily use the older 1.3.3 Release until then.
4. Using the Gradle Node Plugin currently requires that package.json be present at the projectDir level,  i.e. basic/package.json and not basic/src/main/resources/static/package.json. This is inconsistent with the your current project layout. I have created an issue in that project to address this. I'm waiting for a reply.

I have gotten all projects to work successfully except for the security project at this point.

**Comment by gregturn** [comment]
Yeah, I don't think we can fit in Groovy source code next to Java code. I feel that would be too much.

Regarding adjusting the layout of the packages.json, etc., then we may wait until I retuned the layout based on this project I'm currently working on => https://github.com/spring-cloud/spring-cloud-spinnaker

**Comment by MHarris021** [comment]
@gregturn 

No problem on not including the Groovy code. Still need to know which Spring Project to file the CLA against.

**Comment by gregturn** [comment]
Just use Spring Framework.

**Comment by MHarris021** [comment]
CLA signed, do you need me to send you the confirmation number?

**Comment by gregturn** [comment]
Just log it here.

**Comment by MHarris021** [comment]
Confirmation number: 58620130708075029

**Comment by gregturn** [comment]
👍

**Comment by gregturn** [comment]
Since no advancement has been made here and we are on Spring Boot 1.4 as of https://github.com/spring-guides/tut-react-and-spring-data-rest/commit/c58dc0f7c630d1908fc6f4be1012a496fac81fc7, I'm closing this issue.
