### ISSUE TITLE
'npm install' failed. on Windows 10

### ISSUE THREAD

**Issue by xing-kenny** [spring-guides/tut-react-and-spring-data-rest#25]
E:\git\tut-react-and-spring-data-rest>mvn install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] React.js and Spring Data REST - Basic
[INFO] React.js and Spring Data REST - Hypermedia
[INFO] React.js and Spring Data REST - Conditional
[INFO] React.js and Spring Data REST - Events
[INFO] React.js and Spring Data REST - Security
[INFO] React.js and Spring Data REST - Root
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building React.js and Spring Data REST - Basic 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- frontend-maven-plugin:1.0:install-node-and-npm (install node and npm) @ react-and-spring-data-rest-basic ---
[INFO] Installing node version v4.4.5
[INFO] Copying node binary from C:\Users\kenny.m2\repository\com\github\eirslett\node\4.4.5\node-4.4.5-windows-x64.exe to E:\git\tut-react-and-spring-data-rest
\basic\src\main\resources\static\node\node.exe
[INFO] Installed node locally.
[INFO] NPM 3.9.2 is already installed.
[INFO]
[INFO] --- frontend-maven-plugin:1.0:npm (npm install) @ react-and-spring-data-rest-basic ---
[INFO] Running 'npm install' in E:\git\tut-react-and-spring-data-rest\basic\src\main\resources\static
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] React.js and Spring Data REST - Basic .............. FAILURE [  1.071 s]
[INFO] React.js and Spring Data REST - Hypermedia ......... SKIPPED
[INFO] React.js and Spring Data REST - Conditional ........ SKIPPED
[INFO] React.js and Spring Data REST - Events ............. SKIPPED
[INFO] React.js and Spring Data REST - Security ........... SKIPPED
[INFO] React.js and Spring Data REST - Root ............... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.630 s
[INFO] Finished at: 2016-06-13T09:33:47+08:00
[INFO] Final Memory: 27M/183M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project react-and-spring-data-rest-basic: Failed to run task:
'npm install' failed. java.io.IOException: Cannot run program "E:\git\tut-react-and-spring-data-rest\basic\src\main\resources\static\node\node.exe" (in director
y "E:\git\tut-react-and-spring-data-rest\basic\src\main\resources\static"): CreateProcess error=193, %1 不是有效的 Win32 应用程序。 -> [Help 1]

**Comment by gregturn** [comment]
I don't access to Windows let alone Windows 10, so debugging frontend-maven-plugin on such a configuration is outside my reach right now. Have you searched the issues list for the plugin itself?

**Comment by esuarezz** [comment]
It is deployed ok for me in windows 10.
The problem is the budle.js is not found .... do you know something about this gregturn?

**Comment by gregturn** [comment]
bundle.js is supposed to be built by maven using frontend-maven-plugin. I'm afraid I can't really debug a Windows 10 setup.

**Comment by esuarezz** [comment]
UMM I am not sure if this is a windows 10 error... =(

**Comment by esuarezz** [comment]
gregturn, everything working fine on windows 10, keep calm =P! Thank you! cool idea about the implementation!

**Comment by gregturn** [comment]
I believe they vary when there are templates URIs.

**Comment by gregturn** [comment]
Non-issue since this is expected behavior with Spring Data REST.
