### ISSUE TITLE
Live reloading not working

### ISSUE THREAD

**Issue by javier-artiles** [spring-guides/tut-react-and-spring-data-rest#36]
After running `npm run-script watch`, changes in `app.js` are not reflected in the browser after reloading. It seems `webpack.config.js` is not pointing at the correct output directory.

It worked after this change:
```diff
     output: {
-        path: __dirname,
-        filename: './src/main/resources/static/built/bundle.js'
+        path: './target/classes/static/built/',
+        filename: 'bundle.js'
     },
```

**Comment by gregturn** [comment]
You actually have to restart the app to pick up JS only changes. 

Writing to src/main/resources/static is to ensure that Spring Boot plugin properly picks things up for the uber JAR.

**Comment by javier-artiles** [comment]
@gregturn I see. Is there any way to have live reloading while editing the `app.js` file ?

**Comment by gregturn** [comment]
Read the DevTools part of Boot's ref docs. You can adjust the trigger.

**Comment by javier-artiles** [comment]
Thank you @gregturn , I got it working now with DevTools.

**Comment by gregturn** [comment]
👍

**Comment by collier** [comment]
@javier-artiles, any chance you should share how you configured DevTools to autoreload on JS changes? I am working through a similar issue myself.
