### ISSUE TITLE
Test rest

### ISSUE THREAD

**Issue by DiegoECQ** [spring-guides/tut-react-and-spring-data-rest#42]
Hello, i can't see results for this rest: http://localhost:8080/api/employees

![image](https://cloud.githubusercontent.com/assets/19826929/23067288/f9c1edb6-f4f4-11e6-8e21-4bf2ceaa23fd.png)

Thank's

Regards.

**Comment by gregturn** [comment]
Screen shot looks like it's showing the collection just fine. What do you think is missing?

**Comment by DiegoECQ** [comment]
According to the guide should see the data of the employee.

![image](https://cloud.githubusercontent.com/assets/19826929/23067928/c4cbb4b8-f4f7-11e6-9b5d-a5b8b12ed9b2.png)
![image](https://cloud.githubusercontent.com/assets/19826929/23067936/cf222b68-f4f7-11e6-8b84-c0d686e4cc51.png)

Thanks
Regards.

**Comment by gregturn** [comment]
Okay, here's what I did:

1. Checkout latest copy of tutorial.
2. cd into **basic**
3. run **mvn clean spring-boot:run**
4. go into separate shell and execute curl:

```
$ curl localhost:8080/api/employees
{
  "_embedded" : {
    "employees" : [ {
      "firstName" : "Frodo",
      "lastName" : "Baggins",
      "description" : "ring bearer",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/api/employees/1"
        },
        "employee" : {
          "href" : "http://localhost:8080/api/employees/1"
        }
      }
    } ]
  },
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/api/employees"
    },
    "profile" : {
      "href" : "http://localhost:8080/api/profile/employees"
    }
  }
}
```

Looks good to me. What have you done differently, and have you edited any of the code?

**Comment by aprakash-sovrn** [comment]
I'm seeing the exact same issue. Was there ever any resolution to this?

**Comment by gregturn** [comment]
We have a difference in reproduceability. Try wiping your maven cache at .m2 and running the steps I posted.

**Comment by aprakash-sovrn** [comment]
This ended up being a user-error on my part. Missed the @Data annotation on
the @Entity, so wasn't getting the getters/setters. Sorry about that.

**Comment by gregturn** [comment]
np
