### ISSUE TITLE
Empty browser through IntelliJ RUN as Spring Boot.

### ISSUE THREAD

**Issue by Rafal0101** [spring-guides/tut-react-and-spring-data-rest#44]
As in topic. If I run app by RUN command in IntelliJ IDE Employye engine works fine but browser dosen't show the table. If I run app by cmd and mvn ...  :run - everything is OK. Where is the problem?

**Comment by gregturn** [comment]
The react part has to be built which is handled by maven

**Comment by gregturn** [comment]
Seeing no more issue here, I'm closing it.
