### ISSUE TITLE
failed to execute npm install in pom.xml

### ISSUE THREAD

**Issue by arushijain45** [spring-guides/tut-react-and-spring-data-rest#46]
Hello sir,
I was trying spring boot + reactjs + maven for the first time. But importing this project shows me following error in pom.xml. I am new to maven.

> Failed to run task (com.github.eirslett:frontend-maven-plugin:1.2:npm:npm install:generate-resources) 
>  org.apache.maven.plugin.MojoFailureException: Failed to run task at 
>  com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:95) at 
>  org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134) at 
>  org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331) at 
>  org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362) at 
>  org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1) at 
>  org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176) at 
>  org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112) at 
>  org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360) at 
>  org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:
>  52) at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137) at 
>  org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172) at 
>  org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1) at 
>  org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115) at 
>  org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176) at 
>  org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112) at 
>  org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105) at 
>  org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176) at 
>  org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151) at 
>  org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99) at 
>  org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86) at 
>  org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200) at 
>  org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735) at 
>  org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42) at 
>  org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206) at 
>  org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246) at 
>  org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301) at 
>  org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42) at 
>  org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304) at 
>  org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360) at 
>  org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383) at 
>  org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144) at 
>  org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235) at 
>  org.eclipse.core.internal.jobs.Worker.run(Worker.java:55) Caused by: 
>  com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'npm install' failed. (error code 243) at 
>  com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:60) at 
>  com.github.eirslett.maven.plugins.frontend.mojo.NpmMojo.execute(NpmMojo.java:62) at 
>  com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:89) ... 

If possible can you also refer me the sample project in gradle i.e. spring boot + reactjs + gradle project. I am unable to find in gradle build.

**Comment by gregturn** [comment]
Node's "maven central" can be flakey. Try the command a few times to ensure its not just their server timing out.

**Comment by arushijain45** [comment]
I tried to run 5-6 times with 5 minutes interval hoping for same. But the issue persists.

**Comment by PutienkoEN** [comment]
Could it be maven version error? My maven was 3.1 version and refused to run this:
(com.github.eirslett:frontend-maven-plugin:1.2:npm:npm install:generate-resources)
After i updated maven to version 3.3+ app starded.
Also i added some repo, without this repos maven couldn't download this frontend-maven-plugin.
Not shure it's your problem, but at least it worth to try i think.
```
    <repositories>
        <repository>
            <id>spring-releases</id>
            <url>https://repo.spring.io/libs-release</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>spring-releases</id>
            <url>https://repo.spring.io/libs-release</url>
        </pluginRepository>
    </pluginRepositories>
```

**Comment by gregturn** [comment]
Have you tried the maven wrapper, mvnw?

**Comment by ahameleon** [comment]
I'm having issue with mvnw. It does download apache 3.5.0 to my local .m2 repo, but after downloading spring framework its just saying BUILD failure 

Downloading: https://repo.maven.apache.org/maven2/org/springframework/security/spring-security-bom/4.2.1.RELEASE/spring-security-bom-4.2.1.RELEASE.pom
Downloaded: https://repo.maven.apache.org/maven2/org/springframework/security/spring-security-bom/4.2.1.RELEASE/spring-security-bom-4.2.1.RELEASE.pom (4.3 kB at 82 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.739 s
[INFO] Finished at: 2017-07-21T10:58:51+01:00
[INFO] Final Memory: 11M/75M
[INFO] ------------------------------------------------------------------------
[ERROR] No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoGoalSpecifiedException

**Comment by gregturn** [comment]
Looks like you ran it with no arguments. 

`./mvnw -U clean package`

That will force an updated pull maven central, and then clean out target before building the Spring Boot uber jars. 

If that fails I'd suggest cleaning out ~/.m2 and trying again. Sometimes you local maven repo can get corrupted.
