### ISSUE TITLE
Part two, section "Turning on paging from the backend" first curl url missing quotes

### ISSUE THREAD

**Issue by jamesyin96** [spring-guides/tut-react-and-spring-data-rest#47]
Hi,

Greg's tutorial is awesome. But when I follow the instruction, I do find that in Part two, the first section regarding "Turning on paging from the backend", it uses the code curl localhost:8080/api/employees?size=2 whose url is not quoted, which will cause "zsh: no matches found: localhost:8080/api/employees?size=2".

I use curl "localhost:8080/api/employees?size=2" and it works fine. Looks like it's a typo.

**Comment by gregturn** [comment]
Yes, you should wrap a URL with question marks in quotes to avoid this issue. Pull request welcome!

**Comment by jamesyin96** [comment]
Thanks. I just submitted the pull request.
