### ISSUE TITLE
No true security

### ISSUE THREAD

**Issue by benkuly** [spring-guides/tut-react-and-spring-data-rest#53]
I'm not 100% sure, but I think using `#employee?.manager?.name == authentication?.name` can easily  circumvented by an attacker.

Example:
Manager M1 with Employee E1 and Manager M2.
Manager M2 can do PUT or PATCH and set the json "manager" field to {link to M2}. Now E1 has the manager M2 and the security doesn't worked.

**Comment by gregturn** [comment]
There's always room for improvement. Feel free to reopen when you have a PR.
