### ISSUE TITLE
Feature request; Gradle instructions

### ISSUE THREAD

**Issue by erikmartinessanches** [spring-guides/tut-react-and-spring-data-rest#54]
Kindly provide Gradle instructions. I'm not sure how to set up webpack, babel, ract.js and rest.js.

**Comment by jamesyin96** [comment]
Hi, I'm learning this tutorial using Gradle. You just need the build.gradle file. Here's mine.

[build.gradle.txt](https://github.com/spring-guides/tut-react-and-spring-data-rest/files/982234/build.gradle.txt)

**Comment by erikmartinessanches** [comment]
Thanks! Your build.gradle helped out immensely, and I also tried using your package.json and webpack.config.js.

While building however, I'm getting 
```
Time: 2043ms
                                          Asset     Size  Chunks             Chunk Names
    ./src/main/resources/static/built/bundle.js   903 kB       0  [emitted]  main
./src/main/resources/static/built/bundle.js.map  1.06 MB       0  [emitted]  main
    + 229 hidden modules

ERROR in ./src/main/js/client.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./api/uriTemplateInterceptor in /Users/erik/Documents/Dev/repos/appartifact/src/main/js
resolve file
  /Users/erik/Documents/Dev/repos/appartifact/src/main/js/api/uriTemplateInterceptor doesn't exist
  /Users/erik/Documents/Dev/repos/appartifact/src/main/js/api/uriTemplateInterceptor.webpack.js doesn't exist
```
Is there something wrong with my configuration of webpack or something?
![screenshot 2017-05-09_15-03-52](https://cloud.githubusercontent.com/assets/4912935/25852180/cdc5b012-34c8-11e7-9f9e-46330dee5a6c.png)

**Comment by jamesyin96** [comment]
I don't see anything wrong with the webpack.config.js. Try check syntax error in your package.json file, I feel I did see something like this but can't remember exactly. I just upload my project folder into a repository, you can compare the code. I think it's caused by a typo somewhere in you code.
https://github.com/jamesyin96/spring-boot-and-react

**Comment by erikmartinessanches** [comment]
Yeah!

**Comment by seventysixtel** [comment]
Hey All,  I am trying this on windows and cannnot get it working.  I keep getting the following error in the graddle script.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':npmInstall'.
> A problem occurred starting process 'command 'npm.cmd''

**Comment by gregturn** [comment]
This issue was closed five months ago.

**Comment by seventysixtel** [comment]
It is not working for windows.  How would you like to to post it?

**Comment by gregturn** [comment]
Don't jump on old tickets. Start by asking questions on SO about the plugin. I don't use windows so it's hard for me to assist in this fashion.
