### ISSUE TITLE
api  dose not return resource details

### ISSUE THREAD

**Issue by suleimana** [spring-guides/tut-react-and-spring-data-rest#55]
**Issue:** 
basic example dose not return employee details (such as firstName, lastName) . it looks something like this :   
```
$ curl localhost:8080/api/employees
{
  "_embedded" : {
    "employees" : [ {
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/api/employees/1"
        }
      }
    } ]
  }
}
```
**Solution** 
Update to "spring-boot-starter-parent" version from `1.5.1.RELEASE` to `1.5.3.RELEASE`
in [pom.xml#L10](https://github.com/spring-guides/tut-react-and-spring-data-rest/blob/master/basic/pom.xml#L10)

**Comment by ytian90** [comment]
Use 
./mvnw spring-boot:run
also solve the issue for me.

**Comment by tomhickerson** [comment]
Employee data doesn't show with 1.5.10.RELEASE, should I have to roll back to the above version?

**Comment by gregturn** [comment]
Just bumped everything to Spring Boot 1.5.12.RELEASE and it showed the data perfectly.

**Comment by TVerkuijlen** [comment]
I am using Spring Boot 2.0.1.RELEASE and I solved it by creating the getters and setters for the entity.

**Comment by TVerkuijlen** [comment]
https://stackoverflow.com/questions/11803948/lombok-is-not-generating-getter-and-setter
