### ISSUE TITLE
what database are you using?

### ISSUE THREAD

**Issue by headwinds** [spring-guides/tut-react-and-spring-data-rest#56]
I'm enjoying your tutorial - It's easy to follow and get up and running... 

I've gone through it and it's not immediately obvious to me - being basically a junior java dev - what database are you using? I like your explanation of the JPL but where does the data persist to?!

**Comment by gregturn** [comment]
Glad you like it!

It uses H2, an in memory SQL database engine through JPA. If you check Spring Boot's ref docs, you'll find that in dev mode, Boot auto wires H2 when on the classpath to work in embedded mode.

**Comment by headwinds** [comment]
thank you! I'll check it out
