### ISSUE TITLE
How to make this SEO friendly?

### ISSUE THREAD

**Issue by yamennassif** [spring-guides/tut-react-and-spring-data-rest#57]
This approach might be one of the best approaches i have in hand to use my REST services i built on Springboot but still i am concerned  about how to make this SEO friendly. Since it will be a one page app?

**Comment by gregturn** [comment]
The tutorial isn't angled toward SEO but hypermedia. For starters, the hypermedia endpoints are NOT part of the UI, hence building up some sort of dynamic, Spring-based site.xml endpoint doesn't sound that hard, ehh?

If you're talking about bookmarkable points in the UI, then you'd have to investigate something like React Router.

Either way, that would be out of scope for this tutorial.
