### ISSUE TITLE
Can I refer a local copy of nodejs tar file instead of downloading from internet

### ISSUE THREAD

**Issue by rpotnuru** [spring-guides/tut-react-and-spring-data-rest#62]
We are having a restricted environment where downloads are restricted and also uses a private nodejs repo. Because of this reason, we are not able to use this plugin as is and I am guessing some customization might be needed in plugin config in pom file. Any help is greatly appreciated.

I am running into multiple issue when trying to  configure it locally.
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.2:install-node-and-npm (install node and npm) on project react-and-spring-data-rest-basic: Could not download Node.js: Could not download **/Users/rpotn/GIT/ReactSpring/basic/nodejs/v4.4.5/node-v4.4.5-darwin-x64.tar.gz: ClientProtocolException: Target host is not specified -> [Help 1]**
[ERROR]

**Comment by gregturn** [comment]
Actually, I'm not sure how to overcome no connection to the source when it comes to this plugin.
