### ISSUE TITLE
Tutorial - Basic demo

### ISSUE THREAD

**Issue by Silwest** [spring-guides/tut-react-and-spring-data-rest#64]
Hello guys,

I'm trying to finish tutorial on spring page using this git hub repo however when I'm trying to bring to life my first UI I'm getting:
`Uncaught TypeError: client(...).done is not a function`

I'm not sure what I'm doing wrong ... I checked `app.js` and also `client.js` everything looks like in this repo. 

Any ideas? I need to say that I'm new in this matter ...

**Comment by gregturn** [comment]
How did you build and run things?

**Comment by Silwest** [comment]
The answer is simple - I've used new versions of almost everything which was available.
This PR is the answer:
https://github.com/spring-guides/tut-react-and-spring-data-rest/pull/60
