### ISSUE TITLE
could not exec java: Application finished with exit code: 1 -> [help 1] for Basic Tutorial

### ISSUE THREAD

**Issue by sschahil** [spring-guides/tut-react-and-spring-data-rest#65]
I have followed the project structure and all the files as well. However, I keep getting this error saying could not exec java: Application finished with exit code: 1. 

I have looked this up on google and most people say that the path variables are usually set wrong however I have set all my path variables properly as well. And still get this error. My backend java code is working perfectly fine as I am able to see my entries using /api. But I am not able to see the tables.

I would greatly appreciate any help given.

**Comment by sschahil** [comment]
This has been resolved, the devtools was causing the issue for me. After deleting it, I was able to build successfully.

**Comment by gregturn** [comment]
Glad to hear.
