### ISSUE TITLE
After updating an employee, the manager property is lost

### ISSUE THREAD

**Issue by D-Hartley** [spring-guides/tut-react-and-spring-data-rest#67]
When you save an employee update on the front-end, you send an object containing the employee firstName, lastName and description. This is resulting in the manager property being overwritten with nothing.

When the update event is triggered the front-end errors because it cannot find the name of the now null manager.

**Comment by jpizagno** [comment]
A proposed solution is in another ticket. (assuming I understand your message).  
https://github.com/spring-guides/tut-react-and-spring-data-rest/issues/61

**Comment by D-Hartley** [comment]
That solution works, thanks.

I'll close this issue so that there isn't a duplicate.
