### ISSUE TITLE
Feature Request - Client Side routing support

### ISSUE THREAD

**Issue by praveenav** [spring-guides/tut-react-and-spring-data-rest#69]
A standard way for the server to handle redirects to single page application?
Single Page applications have client-side routing. What is the standard/recommended way to handle such scenarios with Spring Security? 

For example,
1. All requests to `/api/*` should be handled by controllers on server
2. Remaining requests should be responded with `index.html`

**Comment by gregturn** [comment]
Spring MVC supports things like "redirect:/some/path" for server side generating redirects. As for client side routine I don't have much experience in that. You'd have to research that outside the scope of this tutorial and pursuant to your client side toolkit (react or whatever).
