### ISSUE TITLE
Separate React frontend from Spring Boot project

### ISSUE THREAD

**Issue by tur-ing** [spring-guides/tut-react-and-spring-data-rest#7]
What would be the **correct approach** to separate the frontend ```resources/*``` from the Spring Boot backend? The first thing that I have noticed is the **CORS issue** if I am running the frontend on my local Apache ```http://localhost/~Marcel/react/*``` and Spring works on ```http://localhost:8080```. I plan to have a couple of different **Spring Boot** and **Node.js** projects that are going to share the same frontend.

**Comment by gregturn** [comment]
That's a great question, but I think it would be better served posted on stackoverflow.com, tagged with spring-boot. It's a common question many would like to read.

**Comment by tur-ing** [comment]
OK. Let's move this to StackOverflow!

**Comment by gregturn** [comment]
Also feel free to include a link back here after you post the question. :)

**Comment by cyc1ingsir** [comment]
I run into the CORS issue as well, not having quite tackled it. Unfortunately, I have not found any question on StackOverflow either.
I assume, this is a quite common approach and some hints on how to configure/inject the CorsRegistry would be much appreciated.
