### ISSUE TITLE
Feels like a Section is missing in setup for react components and frontend dependencies.

### ISSUE THREAD

**Issue by davidbaxter30** [spring-guides/tut-react-and-spring-data-rest#73]
Up until the react part the guide when very smoothly and I didn't even need to reference the end result code in the github but right at the "Defining an HTML template" section it seems to be missing things like setup of the **frontend-maven-plugin** or **webpack**, but its also implied that you wont need to worry about that and it will just work. It was a bit of a blocker for myself as I was going through until I looked up the github code and saw that I needed the exicutables in the pom, the extra component, employee, in the app.js file and the package.json/webpack.conf.js files. Which would be fine if it wasn't implied that we wouldn't need to worry about that. 

Thank you for the great tutorial by the way. I really feel like I'll be able to use this in both my personal and professional projects.

**Comment by simonwangtx** [comment]
I also feel like a section about webpack and the js files in the api folder are missing. Hope the owner could add this content. BTW, this is the best tutorial I've ever seen.
