### ISSUE TITLE
Illegal reflective access by lombok.javac.apt.LombokProcessor

### ISSUE THREAD

**Issue by simbo1905** [spring-guides/tut-react-and-spring-data-rest#74]
Running with Java 9 I get 

> [INFO] React.js and Spring Data REST - Basic .............. FAILURE [ 29.685 s]
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project react-and-spring-data-rest-basic: Fatal error compiling: java.lang.NoClassDefFoundError: com/sun/tools/javac/file/BaseFileObject: com.sun.tools.javac.file.BaseFileObject -> [Help 1]

This appears to be related to https://github.com/rzwitserloot/lombok/issues/1315 which was fixed in https://github.com/rzwitserloot/lombok/commit/05f93771e9aeb6ad0c884f22df4b9fa8c1f6cc2f suggesting that bumping Lombox should fix it.

**Comment by gregturn** [comment]
This tutorial doesn't take the steps needed to support Java 9 (yet).
