### ISSUE TITLE
How to npm run-script watch 

### ISSUE THREAD

**Issue by mbalande1** [spring-guides/tut-react-and-spring-data-rest#77]
"Want to see your JavaScript changes automatically? Run npm run-script watch to put webpack into watch mode. It will regenerate bundle.js as you edit the source"

I am a bit new in this, could you please give me a bit more detail on to how to do this?

**Comment by mbalande1** [comment]
Hi. I would really appreciate if someone could answer this. 
Thanks

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-guides/tut-react-and-spring-data-rest/commit/a35840993a548b46643d0446337c57e09820c4ef
