### ISSUE TITLE
Hot reloading for both frontend and backend

### ISSUE THREAD

**Issue by qiuwei** [spring-guides/tut-react-and-spring-data-rest#8]
It's getting quite tedious that I need to rerun ./mvnw spring-boot:run after I modified single line code in either java source code or javascript. 

Any recommended way to enable hot reloading for both frontend and backend?

**Comment by dsyer** [comment]
You definitely shouldn't have to manually restart for javascript changes if you set your IDE up properly. See the Spring Boot user guide for more details on other tools: http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-reload-static-content, http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#using-boot-hot-swapping, http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#using-boot-devtools

**Comment by gregturn** [comment]
You'd also need to run webpack in the mode where it keeps rebuilding the bundle as well.

**Comment by gregturn** [comment]
Require.js didn't have that problem, but hooking it into Babel.js to convert the ES6 code to ES5 wa too much.

**Comment by qiuwei** [comment]
Thanks for the instructions.

I managed to get it work after read the manual of webpack.

Thanks for the tutorial. For someone rather new to spring and front-end developing, it's invaluable.

**Comment by gregturn** [comment]
I added explicit steps and links in the tutorial to make it easier for people to switch on hot swapping.
