### ISSUE TITLE
Error 404 bundle.js not found

### ISSUE THREAD

**Issue by Lewan110** [spring-guides/tut-react-and-spring-data-rest#81]
My project contains the same files - I did all step by step
Spring Data rest works well, because I getting right data, but when I go to http://localhost:8080 I got no data and an error with bundle.js 

It's weird for me because bundle.js is generated in: \src\main\resources\static\built\bundle.js

**Comment by gregturn** [comment]
You must post a log to pursue this any further. Feel free to reopen the ticket if you find something.
