### ISSUE TITLE
Outdated example

### ISSUE THREAD

**Issue by emeidell** [spring-guides/tut-react-and-spring-data-rest#86]
The example given is using React 15.3.2. I am not sure if this is just an old example or intentionally kept at that version. React is currently on 16.5.0. I do not know enough about Spring yet to feel like i could do the update though.

**Comment by gregturn** [comment]
The front end and back end are separate. 

I simply haven’t updated the react bits in awhile.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-guides/tut-react-and-spring-data-rest/commit/31c21a282fc388ade4058c5d7996b868de58d730.
