### ISSUE TITLE
404 Not Found for request to API

### ISSUE THREAD

**Issue by shlou** [spring-guides/tut-react-and-spring-data-rest#88]
Hi, I'm new to spring, I followed your tutorial step by step and everything went well until this step:
**Touring your REST service**
it seems use command line and enter _curl localhost:8080/api_ will get this:
{
  "_links" : {
    "employees" : {
      "href" : "http://localhost:8080/api/employees"
    },
    "profile" : {
      "href" : "http://localhost:8080/api/profile"
    }
  }
}

but what I got is this:
curl localhost:8080/api
{"timestamp":"2018-09-23T17:10:54.366+0000","status":404,"error":"Not Found","message":"No message available","path":"/api"}

Am I missing something? Thank you.

**Comment by gregturn** [comment]
The code should have an application.properties file that sets the base path. If that isn’t in the tutorial then it should be.

**Comment by shlou** [comment]
I have found the root cause:
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-rest</artifactId>
</dependency>
this should be included in pom.xml, thanks for your explanation and nice tutorial.
