### ISSUE TITLE
Duplicate data load in list data

### ISSUE THREAD

**Issue by dubu** [spring-guides/tut-react-and-spring-data-rest#9]
![shot03](https://cloud.githubusercontent.com/assets/2464016/12835044/f420e846-cbef-11e5-8d18-59ff0ea9ba1a.png)

![shot04](https://cloud.githubusercontent.com/assets/2464016/12835058/1c066138-cbf0-11e5-9d0a-7166e611c0be.png)

in the security 

it load list data and load row data again
Is it duplicate data load?

**Comment by gregturn** [comment]
The security section build on its predecessor that had support for Etags, i.e. optimistic locking. Etag headers aren't returned with collections but instead single resource GETs. Hence the code looks up a collection, and then transforms that collection into a list of promises to fetch each individual resource.

**Comment by gregturn** [comment]
You can see it explained in this earlier section => https://spring.io/guides/tutorials/react-and-spring-data-rest/#_fetching_individual_resources_and_their_headers

**Comment by dubu** [comment]
:+1::+1::+1:
