### ISSUE TITLE
I encountered a package error

### ISSUE THREAD

**Issue by ctlove0523** [spring-guides/tut-react-and-spring-data-rest#90]
when exec mvn clean package encountered the follow exection:

Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm (install node and npm) on project react-and-spring-data-rest-basic: Execution install
 node and npm of goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm failed: A required class was missing while executing com.github.eirslett:frontend-maven-plugin
:1.6:install-node-and-npm: org/apache/http/protocol/HttpContext

**Comment by gregturn** [comment]
Perhaps you hit a server glitch from interwebs. Whole thing works for me.
