### ISSUE TITLE
events example problem

### ISSUE THREAD

**Issue by renxiaobin** [spring-guides/tut-react-and-spring-data-rest#93]
when i re-write and run events example, i found websocket could not update page in the **Chrome**
but it can normally update in other browser, like safari...... Any guys met that? Is sth wrong about Chrome?

**Comment by renxiaobin** [comment]
i mean, if you change employee info in Chrome, the another page in Safari would also change soon;
but while you change employee in Safari, the page opened in Chrome would not change at all...
can someone explain this for me?

**Comment by gregturn** [comment]
That may have been due to a bug in Chrome at the time. I just tested out your scenario using Chrome Version 75.0.3770.142 (Official Build) (64-bit) and Safari Version 12.1.2 (14607.3.9).

**Comment by gregturn** [comment]
Feel free to reopen if you continue to have this issue.
