### ISSUE TITLE
Multiple content-type headers

### ISSUE THREAD

**Issue by PeterJNelsonMN** [spring-guides/tut-react-and-spring-data-rest#94]
I cannot get the "create" to work on the Hypermedia example.  It appears that the client is sending a content-type of "application/json, text/plain" which the REST server rightly sees as invalid.

It also looks like it's passing a string of "[object Object]' as the request body, which might be the root cause.

**Comment by gregturn** [comment]
Are you talking about your own client? Because I just ran `hypermedia` example, and did this with the current frontend client:

<img width="857" alt="Screen Shot 2019-08-08 at 3 29 39 PM" src="https://user-images.githubusercontent.com/311040/62735768-8a4bef80-b9f1-11e9-8b29-3cae30c61882.png">

**Comment by gregturn** [comment]
Feel free to reopen if you continue to have trouble with your client communicating with the server.
